# function and looping

In [17]:
l = [4,6,9,4,5]
for i,value in enumerate(l):
    print('the value of {}item is {}'.format(i,value))

the value of 0item is 4
the value of 1item is 6
the value of 2item is 9
the value of 3item is 4
the value of 4item is 5


In [25]:
l_one = [3,5,4,5,7]
l_two = [4,6,7,8,5]
l_three = [4,2,5,7,9]

for one, two, three in zip(l_one,l_two,l_three):
    print('one:{}, two: {},three:{}'.format(one,two,three))

one:3, two: 4,three:4
one:5, two: 6,three:2
one:4, two: 7,three:5
one:5, two: 8,three:7
one:7, two: 5,three:9


In [30]:
x=0
while x<10:
    x += 1
    print(x)

1
2
3
4
5
6
7
8
9
10


# datatime

In [33]:
import datetime as dt   #import the datatime module 

In [35]:
now = dt.datetime.now()   #assing datatime object representing the current time to now
print(now)

2021-12-07 16:18:33.920620


# random 

In [44]:
import random  #import the rendom module
random.random() #return a random float b/w 0.0 to 1.0

0.9842595627647849

In [46]:
random.randint(10,20) # retunr a random integer b/w 10 and 20

18

In [49]:
l = [23,43,5,22,55]
random.choice(l) #return a random item from l

23

In [ ]:
# 


In [66]:
l_ints =[1,2,3,'',5]  #assing a list of interger with one missing value to l_list
l_floats = []
for i in l_ints:
    try:
        l_floats.append(float(i))
    except:
        l_floats.append(i)
print(l_floats)

[1.0, 2.0, 3.0, '', 5.0]


# pandas 

In [ ]:
#importing data 
pd.read_csv(file_name) # from a csv file
pd.read_table(file_name) #from a delimited text file(like tsv)
pd.read_excel(file_name)
pd.read_sql(query,connetion_object)
pd.read_json(json)string  #reads from a json formatted,url or file
pd.read_html(url) #preses an html url,string or file and extract tables to a list of dataframs
pd.read_clipboard()  #take the content ofour clipborad and preses it to read_table()
pd.DataFrame(dict)   # from a dict ,keys for column names, value for data as lists 


# exporting data 

In [ ]:
df.to_csv(filename)  #writes to csv file
df.to_excel(filename)  #writes to excel file 
df.to _sql(table_name, connection_object)  #write to a sql table
df.to_json(filename)
df.to_html(filename)
df.to_clipboard()  #write to the clipboard


# numpy array

import numpy as np
a = np.array([1,2,3,4,6,5])
print(type(a))

In [91]:
print(a.shape)

(6,)


In [92]:
print(a[0],a[1],a[2])

1 2 3


In [93]:
a[0]=5

In [94]:
print(a)

[5 2 3 4 6 5]


In [110]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [111]:
print(b[0,0],b[0,1],b[1,0])

1 2 4


In [112]:
np.copy(b)

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
b.sort()
print(b)

[[1 2 3]
 [4 5 6]]


In [123]:
b = np.array([[1,2],[3,4],[5,6]])
b.reshape(2,3)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [126]:
np.append(b,[6,8])

array([1, 2, 3, 4, 5, 6, 6, 8])

In [127]:
np.append(b,[7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [131]:
np.delete(b,0,axis =1)  #removing              

array([[2],
       [4],
       [6]])

In [138]:
a= np.array([[8,9],[11,10]])
b= np.array([[1,2],[3,4],[5,6]])
np.concatenate((b,a),axis =0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 8,  9],
       [11, 10]])

In [141]:
np.split(b,3)


[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

In [148]:
#indexing
b[0]=[5,9]
print(b)


[[5 9]
 [3 4]
 [5 6]]
